### ISSUE TITLE
error when parsing not validation errors

### ISSUE THREAD

**Issue by senid231** [JsonApiClient/json_api_client#216]
```
HTTP PATCH (85.41ms)   http://127.0.0.1:4000/api/rest/users/4
Request body  {"data":{"id":"4","type":"users","attributes":{"created_at":null}}}
Response body  {"errors":[{"title":"Param not allowed","detail":"created_at is not allowed.","id":null,"href":null,"code":105,"source":null,"links":null,"status":"400","meta":null}]}

undefined method `fetch' for nil:NilClass
gems/json_api_client-ddbc30d1c017/lib/json_api_client/error_collector.rb:35:in `source_parameter'
gems/json_api_client-ddbc30d1c017/lib/json_api_client/resource.rb:354:in `block in save'
gems/json_api_client-ddbc30d1c017/lib/json_api_client/resource.rb:353:in `each'
gems/json_api_client-ddbc30d1c017/lib/json_api_client/resource.rb:353:in `save'
```

**Comment by senid231** [comment]
`lib/json_api_client/error_collector.rb`
```ruby
def source
  attrs.fetch(:source, {}) || {}
end

def links
   attrs.fetch(:links, {}) || {}
end

def about
 links[:about]
end
```

this will also solve possible issue when links is null

**Comment by Fivell** [comment]
@senid231 , looks like just 400 status handler is missing. Take a look https://github.com/chingor13/json_api_client/blob/master/lib/json_api_client/middleware/status.rb#L34

**Comment by senid231** [comment]
4XX errors is errors that can be related to invalid user input, so errors are returned instead of exception raising

**Comment by Fivell** [comment]
@senid231 , you're talking about 422 error, all other 4XX errors are not about user input, 
examples: 401, 403, 404. So 400 should have same behaviour as other 4XX except 422

**Comment by gaorlov** [comment]
This looks resolved. Please reopen if not
