### ISSUE TITLE
Introduce new JsonApiClient::Errors::SyntaxError

### ISSUE THREAD

**Issue by adis-io** [JsonApiClient/json_api_client#242]
My API sometimes returns this kind of body:
```
{
  "errors": null
}
```

Currently `json_api_client` throws `NoMethodError` with `undefined method 'map' for nil:NilClass` message and stacktrace:
```
/Users/adis/.rvm/gems/ruby-2.3.1/gems/json_api_client-1.3.0/lib/json_api_client/error_collector.rb:66:in `initialize'
/Users/adis/.rvm/gems/ruby-2.3.1/gems/json_api_client-1.3.0/lib/json_api_client/parsers/parser.rb:77:in `new'
/Users/adis/.rvm/gems/ruby-2.3.1/gems/json_api_client-1.3.0/lib/json_api_client/parsers/parser.rb:77:in `handle_errors'
/Users/adis/.rvm/gems/ruby-2.3.1/gems/json_api_client-1.3.0/lib/json_api_client/parsers/parser.rb:13:in `block in parse'
/Users/adis/.rvm/gems/ruby-2.3.1/gems/json_api_client-1.3.0/lib/json_api_client/parsers/parser.rb:8:in `tap'
/Users/adis/.rvm/gems/ruby-2.3.1/gems/json_api_client-1.3.0/lib/json_api_client/parsers/parser.rb:8:in `parse'
/Users/adis/.rvm/gems/ruby-2.3.1/gems/json_api_client-1.3.0/lib/json_api_client/query/requestor.rb:63:in `request'
/Users/adis/.rvm/gems/ruby-2.3.1/gems/json_api_client-1.3.0/lib/json_api_client/query/requestor.rb:12:in `create'
/Users/adis/tengri/src/mod_portal/app/models/api/base.rb:37:in `save'
/Users/adis/.rvm/gems/ruby-2.3.1/gems/json_api_client-1.3.0/lib/json_api_client/resource.rb:138:in `block in create'
```

The problem is I don't know how to see the response from my API. If we introduce new exception derived from `JsonApiClient::Errors::ApiError` then I could fetch response from `e.env.body`.

**Comment by gaorlov** [comment]
This looks resolved. Please reopen if not
