### ISSUE TITLE
Cant save resources  

### ISSUE THREAD

**Issue by wshihadeh** [JsonApiClient/json_api_client#323]
given the following model 
```
module PapiClient #:nodoc
  class ActiveIngredient < JsonApiClient::Resource #:nodoc:
    self.site = 'http://127.0.0.1:8080'
  end
end
```

when I try to save and object I get the following error 
```
PapiClient::ActiveIngredient.new(name: 'test').save
``` 

error 
```
JsonApiClient::Errors::ServerError: JsonApiClient::Errors::ServerError
```

and from the backend 
```
I, [2019-01-03T15:09:27.378373 #3368]  INFO -- : [1fd7f7d2-d241-402a-961f-a87bba8aca83] Started POST "/active_ingredients" for 127.0.0.1 at 2019-01-03 15:09:27 +0100
I, [2019-01-03T15:09:27.379230 #3368]  INFO -- : [1fd7f7d2-d241-402a-961f-a87bba8aca83] Processing by V1::ActiveIngredientsController#create as application/vnd.api+json
I, [2019-01-03T15:09:27.489884 #3368]  INFO -- : [1fd7f7d2-d241-402a-961f-a87bba8aca83] Completed 500 Internal Server Error in 111ms
F, [2019-01-03T15:09:27.490627 #3368] FATAL -- : [1fd7f7d2-d241-402a-961f-a87bba8aca83]
F, [2019-01-03T15:09:27.535929 #3368] FATAL -- : [1fd7f7d2-d241-402a-961f-a87bba8aca83] NameError (undefined local variable or method `byebug' for #<V1::ActiveIngredientsController:0x007fc9d918bb40>):
F, [2019-01-03T15:09:27.535993 #3368] FATAL -- : [1fd7f7d2-d241-402a-961f-a87bba8aca83]
F, [2019-01-03T15:09:27.536023 #3368] FATAL -- : [1fd7f7d2-d241-402a-961f-a87bba8aca83] app/controllers/v1/active_ingredients_controller.rb:43:in `active_ingredient_params'
[1fd7f7d2-d241-402a-961f-a87bba8aca83] app/controllers/v1/active_ingredients_controller.rb:18:in `create'
```

after some debugging I found that the client is not sending the attributes of the model to the server. the params object only contains "controller" and "action"
```
<ActionController::Parameters {"controller"=>"v1/active_ingredients", "action"=>"create"}
```

**Comment by wshihadeh** [comment]
it turns out that i need to register a new content type in my backend app 
```
Mime::Type.register 'application/vnd.api+json', :json
```
